### ISSUE TITLE
Can you share the data dump?

### ISSUE THREAD

**Issue by cutd** [elliotwutingfeng/Twitter200M#1]
I want to analysis the twitter data, can you share the data dump?

**Comment by elliotwutingfeng** [comment]
Hi there, thanks for the question. I am not keen on sharing the dataset via any communication channel in order to keep this repository compliant with the [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines)

The Jupyter notebook and findings, which are general in nature and do not violate twitter user privacy, is as far as I'll go.

Good luck.
